# Generated by Django 5.1.15 on 2026-09-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Картинка')),
                ('image_url', models.URLField(blank=True, verbose_name='URL картинки (если нет файла)')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка (URL или name)')),
                ('card_type', models.CharField(choices=[('youtube', 'YouTube видео'), ('playlist', 'YouTube плейлист'), ('internal', 'Внутренняя страница'), ('telegram', 'Telegram канал'), ('external', 'Внешняя ссылка')], default='youtube', max_length=20, verbose_name='Тип')),
                ('bg_color', models.CharField(blank=True, help_text='Например #f8c512', max_length=20, verbose_name='Фон карточки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('duration', models.CharField(blank=True, max_length=16)),
                ('channel_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order', '-published'],
            },
        ),
    ]
