# Generated by Django 6.0.5 on 2026-05-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='Аудиофайл')),
            ],
        ),
    ]
