# Generated by Django 6.0.5 on 2026-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiyadhAsSalihin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('audio_file', models.FileField(upload_to='riyad_useimin/audio/', verbose_name='Аудио файл')),
                ('matn_pdf', models.FileField(blank=True, null=True, upload_to='riyad_useimin/pdf/', verbose_name='Матн (PDF)')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Вопросы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Урок Рияд ас-Салихин',
                'verbose_name_plural': 'Уроки Рияд ас-Салихин',
                'ordering': ['order', 'id'],
            },
        ),
    ]
