# Generated by Django 6.0.5 on 2026-05-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_riyadhassalihin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riyadhassalihin',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='riyadhassalihin',
            name='matn_pdf',
        ),
        migrations.AddField(
            model_name='riyadhassalihin',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на аудио (S3)'),
        ),
    ]
